### ISSUE TITLE
consider to use kubernetes.default.svc.cluster.local instead of api.<cluster_name>.<base_domain>

### ISSUE THREAD

**Issue by rbo** [yasensim/nsxt-ocp4#1]
Hi Yasen,

in 
 - https://github.com/yasensim/nsxt-ocp4/blob/master/openshift4/cluster-network-17-nsx-ncp-config.yaml#L106
 - https://github.com/yasensim/nsxt-ocp4/blob/master/openshift4/cluster-network-20-nsx-node-agent-config.yaml#L13

you are using `api.<cluster_name>.<base_domain>` - of those pods they are using the configuration is running inside the SDN it is better to use `kubernetes.default.svc.cluster.local` it is more generic.

Additional: With openshift 4 it is supported to change the certificate of api.<cluster_name>.<base_domain>, that means you have to trust to another root ca. (`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` will not match)

Thanks
robert

**Comment by rbo** [comment]
If you want to use `kubernetes.default.svc.cluster.local` and avoid container restarts because `kubernetes.default.svc.cluster.local` is not ready yet. You can use a initcontainer to check `kubernetes.default.svc.cluster.local`, here an example (different hostname):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: check-tcp
    image: rhel7/rhel-tools
    command: ['sh', '-c', 'while true ; do echo "Try to connect " ; nc -z myserver 8080 && break; sleep 5; done; echo "Eventserver is running..."']
  - name: check-nslookup
    image: busybox
    command: ['sh', '-c', 'while true; do nslookup mydb || break ; sleep 2 ; echo "waiting for mydb"; done;']
```
